### ISSUE TITLE
certbot: acme.errors.ClientError: "up" Link header missing

### ISSUE THREAD

**Issue by v2px** [jgnagy/bullion#33]
Hi, it's me again :)

I'm not sure if I'm doing something wrong but when trying to request a cert with certbot like so:
`certbot certonly --server http://acme.example.com:9292/acme/directory --domain ldap.example.com --standalone`

I get this error:
`An unexpected error occurred:
acme.errors.ClientError: "up" Link header missing`

I'm sure I must have overlooked something - can you tell me what I'm doing wrong?
Thanks!

**Comment by jgnagy** [comment]
This is a bug with how I'm handling the ACME response to challenge clients. I've only seen this `up` Link header being used by certbot. [RFC 8555](https://datatracker.ietf.org/doc/html/rfc8555) seemed to indicate that [only the `index` Link relation was _required_](https://datatracker.ietf.org/doc/html/rfc8555#section-7.1), making be believe that others (such as `up`) are optional. This was further proven by both cert-manager and the Ruby ACME client (used in my integration tests) working fully, end-to-end, with Bullion without this `up` Link relation.

I hadn't attempted to use certbot against Bullion yet myself, but I am able to report that I can fully reproduce the problem locally.

I'll work on adding this Link relation today.

Thanks for your patience and for reporting bugs like these!

**Comment by v2px** [comment]
You're amazing, thanks for the quick response!
Sadly certbot still isn't happy and gives me the same error.
This happens when challenge.status is not (yet?) "valid" in https://github.com/jgnagy/bullion/blob/66e88a5ef3e8ee522f4bee35f222528017cd37dd/lib/bullion/services/ca.rb#L356

Thanks again for the help!

**Comment by jgnagy** [comment]
> Sadly certbot still isn't happy and gives me the same error.

I suppose this error could still happen if the status isn't valid, but at this point in the code, the challenge was already attempted. If the status isn't valid, that likely means that the challenge failed. Certbot would have attempted an HTTP01 challenge

I'll move the header to outside that conditional so it is always available, which should at least give more info about why it failed.

**Comment by jgnagy** [comment]
https://github.com/jgnagy/bullion/commit/39d07ece2c600bc01e316755aed3e5ce8935c6f0 (or gem version 0.5.1) should help.

**Comment by v2px** [comment]
Yes thank you, I noticed that I tried the wrong DNS name.
Interestingly enough, the challenge still fails as the expected challenge thumbprint doesn't match the one provided by the certbot server. Should I create a new issue for this?

**Comment by jgnagy** [comment]
Yes please do. Sounds like a different error to look into.
